[package]
name = "personal_site"
version = "0.1.0"
authors = ["Carson Rajcan"]
edition = "2018"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
out-dir = "client"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"
derive_more = "0.99.17"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'Document',
  'Element',
  'Event',
  'HtmlElement',
  'HtmlInputElement',
  'KeyboardEvent',
  'Node',
  'Window',
]
